In [1]:
import numpy as np

## DataTypes & Attribute

In [2]:
array1 = np.array([1,2,3]) 

In [3]:
array1

array([1, 2, 3])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array2 = np.array([[1,2,3],[4,5,6]])
array2
type(array2)

numpy.ndarray

In [6]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
array3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
array4 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[3,4,7],[8,9,10],[10,23,76]]])
array4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 3,  4,  7],
        [ 8,  9, 10],
        [10, 23, 76]]])

In [11]:
array5 = np.array([[[1,2,3],[3,4,5],[6,7,8]],
                   [[2,3,6],[7,8,9],[9,80,65]]])
array5

array([[[ 1,  2,  3],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 2,  3,  6],
        [ 7,  8,  9],
        [ 9, 80, 65]]])

In [17]:
array5.shape

(2, 3, 3)

In [18]:
array1.shape

(3,)

In [19]:
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
array2.shape

(2, 3)

In [21]:
arraydemo = np.array([[1,2,3],[3,4,5],[6,5,3]])

In [22]:
arraydemo

array([[1, 2, 3],
       [3, 4, 5],
       [6, 5, 3]])

In [23]:
arraydemo.shape

(3, 3)

In [25]:
array = np.array([[[1,2,3],[2,3,5]],[[1,2,3],[3,4,5]]])

In [26]:
array


array([[[1, 2, 3],
        [2, 3, 5]],

       [[1, 2, 3],
        [3, 4, 5]]])

In [27]:
array.shape

(2, 2, 3)

In [38]:
a1 = np.array([[[1,2,3],
                [2,3,5],
                [1,5,6]],
               
               
               [[1,2,3],
                [3,4,5],[2,3,5]]])

In [39]:
a1

array([[[1, 2, 3],
        [2, 3, 5],
        [1, 5, 6]],

       [[1, 2, 3],
        [3, 4, 5],
        [2, 3, 5]]])

In [40]:
a1.shape

(2, 3, 3)

In [41]:
a1.ndim

3

In [42]:
array1.ndim, array2.ndim, array3.ndim, array4.ndim

(1, 2, 2, 3)

In [43]:
arraydemo.ndim

2

In [44]:
array4

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 3,  4,  7],
        [ 8,  9, 10],
        [10, 23, 76]]])

In [45]:
array4.size 

18

In [48]:
array4.dtype

dtype('int64')

In [47]:
type(array4)

numpy.ndarray

In [50]:
# crate a data frame from numpy array

import pandas as pd

df = pd.DataFrame(arraydemo)
df

0  1  2
0  1  2  3
1  3  4  5
2  6  5  3

## Creating array

In [51]:
demo_array = np.array([1,2,3])
demo_array

array([1, 2, 3])

In [53]:
ones = np.ones((2,3), dtype=int)
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [54]:
type(ones)

numpy.ndarray

In [58]:
zeros = np.zeros((3,4),dtype = int)

In [59]:
zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [63]:
range_array = np.arange(0,10,5)

In [64]:
range_array

array([0, 5])

In [65]:
random_array = np.random.randint(0, 10, size = (2,3))
random_array

array([[5, 0, 0],
       [8, 2, 4]])

In [66]:
random_array.shape

(2, 3)

In [67]:
random_array.size

6

In [68]:
random_array_2 = np.random.random((2,3))

In [69]:
random_array_2

array([[0.94799483, 0.2706631 , 0.83306613],
       [0.31990322, 0.89519528, 0.80447161]])

In [70]:
random_array_2.shape

(2, 3)

In [71]:
dataframe = pd.DataFrame(random_array_2) 

In [72]:
dataframe

0         1         2
0  0.947995  0.270663  0.833066
1  0.319903  0.895195  0.804472