# Introduction To Scikit-Learn(sklearn)


This notebook demonstrates some of the most userful functions of the Scikit-Learn library.

In [1]:
# Standard import
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

 # An end-to-end Scikit-Learn workflow

In [2]:
# Get the data reday

heart_disease = pd.read_csv('data/heart-disease.csv')
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

# Different name for:
    * x = features , features variables, data
    * y = labels, targets, target variables

In [3]:
# create x (features matrix)
x = heart_disease.drop('target', axis = 1)

# create y (labels)
y = heart_disease['target']

In [4]:
#choose the right model and hyperparameters

from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier() # n_estimators = 10 to 100, 10 is default

#keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 'warn',
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [5]:
import warnings
warnings.filterwarnings("default") # "ignore" can be used for ingore all warnings

In [6]:
# fit the model to training data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25)

In [7]:
clf.fit(x_train, y_train);

/home/a2r7i4f3/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [8]:
x_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
142   42    0   2       120   209    0        1      173      0      0.0   
261   52    1   0       112   230    0        1      160      0      0.0   
181   65    0   0       150   225    0        0      114      0      1.0   
112   64    0   2       140   313    0        1      133      0      0.2   
152   64    1   3       170   227    0        0      155      0      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
291   58    1   0       114   318    0        2      140      0      4.4   
165   67    1   0       160   286    0        0      108      1      1.5   
215   43    0   0       132   341    1        0      136      1      3.0   
61    54    1   1       108   309    0        1      156      0      0.0   
77    59    1   1       140   221    0        1      164      1      0.0   

     slope  ca  thal  
142      1   0     2  
261      2   1     2  
181      1   3     3  
112      2   0     3  
152      1   0     3  
..     ...  ..   ...  
291      0   3     1  
165      1   3     2  
215      1   0     3  
61       2   0     3  
77       2   0     2  

[76 rows x 13 columns]

In [9]:
y_test

142    1
261    0
181    0
112    1
152    1
      ..
291    0
165    0
215    0
61     1
77     1
Name: target, Length: 76, dtype: int64

In [10]:
y_preds = clf.predict(x_test)
y_preds

array([1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1])

In [11]:
# Evaluate the model

clf.score(x_train, y_train)

0.986784140969163

In [12]:
clf.score(x_test, y_test)

0.7236842105263158

In [13]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.73      0.71      0.72        38
           1       0.72      0.74      0.73        38

    accuracy                           0.72        76
   macro avg       0.72      0.72      0.72        76
weighted avg       0.72      0.72      0.72        76



In [14]:
confusion_matrix(y_test, y_preds)

array([[27, 11],
       [10, 28]])

In [15]:
confusion_matrix(y_test, y_preds)

array([[27, 11],
       [10, 28]])

In [16]:
accuracy_score(y_test, y_preds)

0.7236842105263158

In [17]:
#improve a model
#try different amount of n_estimators

np.random.seed(0)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators..")
    clf = RandomForestClassifier(n_estimators = i).fit(x_train, y_train)
    print(f"Model Accuracy on test set: {clf.score(x_test, y_test) * 100:.2f}%")
    print("")


Trying model with 10 estimators..
Model Accuracy on test set: 77.63%

Trying model with 20 estimators..
Model Accuracy on test set: 76.32%

Trying model with 30 estimators..
Model Accuracy on test set: 75.00%

Trying model with 40 estimators..
Model Accuracy on test set: 81.58%

Trying model with 50 estimators..
Model Accuracy on test set: 76.32%

Trying model with 60 estimators..
Model Accuracy on test set: 72.37%

Trying model with 70 estimators..
Model Accuracy on test set: 76.32%

Trying model with 80 estimators..
Model Accuracy on test set: 76.32%

Trying model with 90 estimators..
Model Accuracy on test set: 76.32%



In [18]:
# save model and load it 
import pickle

pickle.dump(clf, open("random_forest_model_1.pkl","wb"))

/home/a2r7i4f3/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: ResourceWarning: unclosed file <_io.BufferedWriter name='random_forest_model_1.pkl'>
  after removing the cwd from sys.path.


In [19]:
loaded_model = pickle.load(open("random_forest_model_1.pkl", "rb"))
loaded_model.score(x_test, y_test)

/home/a2r7i4f3/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: ResourceWarning: unclosed file <_io.BufferedReader name='random_forest_model_1.pkl'>
  """Entry point for launching an IPython kernel.


0.7631578947368421

In [20]:
loaded_model.score(x_train, y_train)

1.0

In [21]:
import sklearn
sklearn.show_versions()


System:
    python: 3.7.4 (default, Aug 13 2019, 20:35:49)  [GCC 7.3.0]
executable: /home/a2r7i4f3/anaconda3/bin/python
   machine: Linux-5.3.0-42-generic-x86_64-with-debian-buster-sid

Python deps:
       pip: 19.2.3
setuptools: 41.4.0
   sklearn: 0.21.3
     numpy: 1.17.2
     scipy: 1.3.1
    Cython: 0.29.13
    pandas: 0.25.1


In [22]:
print("")

###  1. Getting our data ready to be used with machine learning
 
    Three Main things to do:
        1. Split the data into features and labels (usally `x` and `y`)
        2. Filling (also called inputing) or disregarding missing values
        3. converting no-numerical values to numerical values (also called feature encoding)
 

In [23]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [24]:
x = heart_disease.drop('target', axis = 1)
x.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [25]:
y = heart_disease["target"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25) # 25% data for testing, 75% data for training


In [27]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((227, 13), (76, 13), (227,), (76,))

In [28]:
x.shape

(303, 13)

In [29]:
x.shape[0] * .75

227.25

In [30]:
227+76

303

In [31]:
len(heart_disease)

303

### 1.1 Make sure it's all numerical

In [32]:
car_sales = pd.read_csv('data/car-sales-extended.csv')
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [33]:
len(car_sales), type(car_sales)

(1000, pandas.core.frame.DataFrame)

In [34]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [35]:
# split into x/y
x = car_sales.drop('Price', axis = 1)
y = car_sales['Price']

# split into training and test
x_train, x_test, y_train, y_test = train_test_split(x,
                                                    y,
                                                    test_size = 0.25)

In [36]:
x_train.shape, x.shape[0] * .75

((750, 4), 750.0)

In [37]:
car_sales['Doors'].value_counts()

4    856
5     79
3     65
Name: Doors, dtype: int64

In [38]:
car_sales['Odometer (KM)'].value_counts()

73869     2
129188    2
244404    1
10954     1
10953     1
         ..
40285     1
131587    1
95579     1
38233     1
184320    1
Name: Odometer (KM), Length: 998, dtype: int64

In [39]:
# build machine learning model

from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x_train, y_train)
model.score(x_test, y_test)


/home/a2r7i4f3/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


ValueError: could not convert string to float: 'Nissan'

In [ ]:
# turn categories into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot",
                                   one_hot,
                                   categorical_features)],
                                   remainder = 'passthrough')

transformed_x = transformer.fit_transform(x)
transformed_x

In [40]:
pd.DataFrame(transformed_x).head()

NameError: name 'transformed_x' is not defined

In [41]:
dummies = pd.get_dummies(car_sales[['Make', 'Colour', 'Doors']])
dummies

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4         0           1            0            0             0   
1        5         1           0            0            0             0   
2        4         0           1            0            0             0   
3        4         0           0            0            1             0   
4        3         0           0            1            0             0   
..     ...       ...         ...          ...          ...           ...   
995      4         0           0            0            1             1   
996      3         0           0            1            0             0   
997      4         0           0            1            0             0   
998      4         0           1            0            0             0   
999      4         0           0            0            1             0   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0              0             0           0             1  
1              1             0           0             0  
2              0             0           0             1  
3              0             0           0             1  
4              1             0           0             0  
..           ...           ...         ...           ...  
995            0             0           0             0  
996            0             0           0             1  
997            1             0           0             0  
998            0             0           0             1  
999            1             0           0             0  

[1000 rows x 10 columns]

In [42]:
# refit the modle
np.random.seed(42)
x_train, x_test, y_train, y_test = train_test_split(transformed_x,
                                                    y,
                                                    test_size = 0.2)
model.fit(x_train, y_train)

NameError: name 'transformed_x' is not defined

In [43]:
model.score(x_test, y_test)

NotFittedError: This RandomForestRegressor instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

## What if there were misising values?

    1. Fill them with some value (also known as imputation)
    2. Remove the samples with missing data altogether.

In [44]:
# import car sales missing data

car_sales_missing = pd.read_csv('data/car-sales-extended-missing-data.csv')
car_sales_missing.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [45]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [46]:
# Create x and y

x = car_sales_missing.drop('Price', axis = 1)
y = car_sales_missing['Price']

In [47]:
# Convert data to numbers
# Turn the caategories into number

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ['Make', 'Colour', 'Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one hot', one_hot, categorical_features)],
                                remainder = 'passthrough')

transformed_x = transformer.fit_transform(x)
transformed_x

ValueError: Input contains NaN

In [48]:
car_sales_missing.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

## Option 1: Fill missing data with pandas

In [49]:
# Fill the 'Make' column

car_sales_missing['Make'].fillna('missing', inplace = True)

# Fill the "Colour" Column

car_sales_missing['Colour'].fillna('missing', inplace = True)

# Fill the 'Odomoter (KM)' column
car_sales_missing['Odometer (KM)'].fillna(car_sales_missing['Odometer (KM)'].mean(), inplace = True)

# Fill the 'Doors' column
car_sales_missing['Doors'].fillna(4, inplace = True)

In [50]:
car_sales_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [51]:
# Remove rows with missing Price value
car_sales_missing.dropna(inplace = True)
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [52]:
len(car_sales_missing)

950

In [53]:
x = car_sales_missing.drop('Price', axis = 1)
y = car_sales_missing['Price']

In [54]:

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ['Make', 'Colour', 'Doors']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',
                                  one_hot,
                                  categorical_features)],
                                  remainder = 'passthrough')

transformed_x = transformer.fit_transform(car_sales_missing)
transformed_x

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

## Opting 2: Fill missing values with Scikit-Learn

In [55]:
car_sales_missing = pd.read_csv('data/car-sales-extended-missing-data.csv')
car_sales_missing.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [56]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [57]:
car_sales_missing.dropna(subset = ['Price'], inplace = True)
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [58]:
x = car_sales_missing.drop('Price', axis = 1)
y = car_sales_missing['Price']

In [59]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Fill categorical values wih 'missing' & numerical values with mean
cat_imputer = SimpleImputer(strategy='constant', fill_value='missing')
door_imputer = SimpleImputer(strategy='constant', fill_value=4)
num_imputer = SimpleImputer(strategy='mean')

# Define columns
cat_features = ['Make', 'Colour']
door_features = ['Doors']
num_features = ['Odometer (KM)']

# Create an imputer (something that fills missing data) 

imputer = ColumnTransformer([
    ('cat_imputer', cat_imputer, cat_features),
    ('door_imputer', door_imputer, door_features),
    ('num_imputer', num_imputer, num_features)
])

filled_x = imputer.fit_transform(x)
filled_x

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], dtype=object)

In [60]:
car_sales_filled = pd.DataFrame(filled_x,
                                columns= ['Make', 'Colour', 'Doors', 'Odometer (KM)'])
car_sales_filled.head()

Make Colour Doors Odometer (KM)
0   Honda  White     4         35431
1     BMW   Blue     5        192714
2   Honda  White     4         84714
3  Toyota  White     4        154365
4  Nissan   Blue     3        181577

In [61]:
car_sales_filled.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [62]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ['Make', 'Colour', 'Odometer (KM)']
one_hot = OneHotEncoder()
transformer = ColumnTransformer([('one_hot',
                                  one_hot,
                                  categorical_features)],
                               remainder='passthrough')
transformed_x = transformer.fit_transform(car_sales_filled)
transformed_x

<950x913 sparse matrix of type '<class 'numpy.float64'>'
	with 3800 stored elements in Compressed Sparse Row format>

In [63]:
# Now we've got our data as numbers and filled (no missing values)
# Let's fit a model
np.random.seed(0)

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(transformed_x,
                                                    y,
                                                    test_size = 0.2)
model = RandomForestRegressor(n_estimators = 100)
model.fit(x_train, y_train)
model.score(x_test, y_test)

-0.10385991629996161

In [64]:
len(car_sales_filled), len(car_sales)

(950, 1000)

## Choosing the right estimator / algorithm
Scikit-Learn uses estimator as another term for machine learning model for algorithm.

    * Classification - predicting whether a sample is one thing or another
    * Regression - predicting a number
    
    Scikit_Learn machine learnging map...https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

## Picking a machine learning model for a regression problem

In [65]:
# Import Boston housing dataset 
from sklearn.datasets import load_boston
boston = load_boston()
boston;

/home/a2r7i4f3/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [66]:
boston_df = pd.DataFrame(boston['data'], columns=boston['feature_names'])
boston_df['target'] = pd.Series(boston['target'])
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [67]:
len(boston_df)

506

In [68]:
# Ridge regression model 
from sklearn.linear_model import Ridge

# Set up random seed
np.random.seed(42)

# Split into train and test sets
x = boston_df.drop('target', axis = 1)
y = boston_df['target']

x_train, x_test, y_train, y_test = train_test_split(x,
                                                    y,
                                                    test_size = 0.2)

# Instantiate Ridge model
model = Ridge()
model.fit(x_train, y_train)

# Check the score of the Ridge model on test data
model.score(x_test, y_test)

0.6662221670168522

In [69]:
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [70]:
# Random Forest Regressor

from sklearn.ensemble import RandomForestRegressor

# setup random seed
np.random.seed(42)

#split the data
x = boston_df.drop('target', axis = 1)
y = boston_df['target']

# instantiate RandomForestRegressor
rf = RandomForestRegressor(n_estimators=100)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.8896648705127477

In [71]:
#Check the Ridge model again
model.score(x_test, y_test)

0.6662221670168522

## Choosing an estimator for a classification problem
map... https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html

In [72]:
heart_disease = pd.read_csv("data/heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [73]:
len(heart_disease)

303

Consulting the map it says to try LinearSVC

In [74]:
# Import the LinearSVC estimator class
# Linear Support Vector Classificatio

from sklearn.svm import LinearSVC

# Setup reandom seed
np.random.seed(42)

# Make the data ready
x = heart_disease.drop('target', axis=1)
y = heart_disease['target']

# Split the data

x_train, x_test, y_train, y_test = train_test_split(x,
                                                    y,
                                                    test_size = 0.2)

# Instantiate LinearSVC

clf = LinearSVC()
clf.fit(x_train, y_train)
clf.score(x_test, y_test)



/home/a2r7i4f3/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.8688524590163934

    1. If you have structured data, use ensemble methods
    2. If you have unstructured data , use deep learning or transfer learning

In [75]:
heart_disease['target'].value_counts()

1    165
0    138
Name: target, dtype: int64

In [76]:
from sklearn.linear_model import Ridge

# Setup reandom seed
np.random.seed(42)

# Make the data ready
x = heart_disease.drop('target', axis=1)
y = heart_disease['target']

# Split the data

x_train, x_test, y_train, y_test = train_test_split(x,
                                                    y,
                                                    test_size = 0.2)

# Instantiate Ridge

clf = Ridge()
clf.fit(x_train, y_train)
clf.score(x_test, y_test)

0.5351464847153696

## Fit the model/algorithm on our data and use it to make predictions

## Fitting the model to the data

In [77]:
x.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [78]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [79]:
y.tail()

298    0
299    0
300    0
301    0
302    0
Name: target, dtype: int64

## Make predictions using machine learning model

2 ways to make prediction:
1. `predict()`
2. `predict_proba()`

In [80]:
clf.predict(x_test)

array([ 2.07944123e-01,  6.32780475e-01,  7.17020716e-01,  4.62746967e-02,
        9.33542387e-01,  8.28069879e-01,  5.54142159e-01, -3.11527712e-01,
       -1.25005849e-01,  5.05724299e-01,  6.73182713e-01,  2.29665165e-01,
        8.36206112e-01,  1.03146361e-01,  1.10357710e+00,  9.04975940e-01,
        1.08493583e+00,  2.12542895e-01, -1.38880204e-01, -2.81078949e-02,
        6.09782309e-01, -5.42847631e-02,  3.54247837e-01,  6.82380639e-01,
        8.85340933e-01,  6.07907644e-01,  8.19454678e-01,  5.35691469e-01,
       -9.96822781e-02,  8.93797304e-01,  6.25728850e-02,  7.51767395e-02,
       -1.45774816e-01,  2.43427135e-01,  6.89841208e-01,  1.98356510e-01,
        6.66585905e-01,  7.77919959e-01,  6.85516969e-01,  7.55537359e-01,
        4.94601851e-01,  6.43380361e-01,  7.55216583e-01,  6.73500579e-01,
        7.46334390e-01, -1.86674714e-01,  6.64022995e-01,  9.16284227e-01,
        2.25478808e-01, -3.11608187e-04,  1.57922692e-01, -1.25168370e-01,
        7.81927741e-01,  

In [81]:
y_test # y_true

179    0
228    0
111    1
246    0
60     1
      ..
249    0
104    1
300    0
193    0
184    0
Name: target, Length: 61, dtype: int64

In [82]:
# Compare predictions to truth labels to evaluate the model
y_preds = clf.predict(x_test)
np.mean(y_preds == y_test) 

0.0

In [83]:
clf.score(x_test, y_test)

0.5351464847153696

In [84]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)

ValueError: Classification metrics can't handle a mix of binary and continuous targets

Make prediction with `predict_proba()`


In [85]:
# predict_proba() returns probabilities of a classification label 
clf.predict_proba(x_test[:5])

AttributeError: 'Ridge' object has no attribute 'predict_proba'

In [86]:
clf.predict(x_test[:5])

array([0.20794412, 0.63278048, 0.71702072, 0.0462747 , 0.93354239])

In [87]:
heart_disease['target'].value_counts()

1    165
0    138
Name: target, dtype: int64

`predict()` can also be used for regression models

In [88]:
boston_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [89]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

#create data
x = boston_df.drop('target', axis=1)
y = boston_df['target']

#split into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

#instantiate and fit model
model = RandomForestRegressor(n_estimators=100).fit(x_train, y_train)
model.score(x_test, y_test)

0.873969014117403

In [90]:
#make prediction 
y_preds = model.predict(x_test)
y_preds

array([23.002, 30.826, 16.734, 23.467, 16.853, 21.725, 19.232, 15.239,
       21.067, 20.738, 19.516, 19.83 ,  8.885, 21.918, 19.477, 26.465,
       19.347,  8.039, 45.414, 14.542, 24.564, 23.941, 14.481, 23.077,
       15.031, 14.625, 21.171, 14.164, 19.251, 20.717, 19.433, 23.242,
       31.091, 20.39 , 14.294, 15.796, 34.3  , 19.155, 20.639, 24.464,
       18.779, 29.688, 45.257, 19.449, 22.334, 13.727, 15.408, 24.621,
       18.783, 28.247, 21.411, 33.961, 17.011, 26.312, 44.904, 21.988,
       15.65 , 32.316, 22.281, 20.394, 25.405, 34.266, 28.938, 18.857,
       26.909, 17.154, 13.731, 23.079, 28.508, 15.818, 20.41 , 28.38 ,
       10.153, 21.336, 22.393,  7.093, 20.059, 45.424, 10.964, 12.914,
       21.387, 12.29 , 20.234,  9.065, 20.218, 26.736, 15.531, 23.228,
       23.568, 17.719, 21.64 ,  7.991, 19.6  , 18.7  , 22.292, 19.665,
       38.756, 13.03 , 12.49 , 13.406, 20.219, 23.898])

In [91]:
np.array(y_test.head())

array([23.6, 32.4, 13.6, 22.8, 16.1])

In [92]:
# compare the prediction to the truth

from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)

2.1226372549019623

## Evaluating a machine learning model
Three ways to evaluate Scikit-Learn model/estimators
1. Estimator `score` method
2. The `scoring` parameter
3. Problem-specific metric functions

## Evaluationg a model with the score method

In [93]:
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

x = heart_disease.drop('target', axis=1)
y = heart_disease['target']

#split into train and test sets

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

# instantiate and fit model
clf = RandomForestClassifier()
clf.fit(x_train, y_train)

/home/a2r7i4f3/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [94]:
clf.score(x_train, y_train)

1.0

In [95]:
clf.score(x_test, y_test)

0.8524590163934426

In [98]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

#create the data
x = boston_df.drop('target', axis=1)
y = boston_df['target']

#split into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x,
                                                    y,
                                                    test_size=0.2)
model = RandomForestRegressor(n_estimators=100).fit(x_train, y_train)

In [97]:
model.score(x_test, y_test)

0.8477414419760558

## Evaluating a model using the `scoring` parameter

In [102]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

#create the data
x = heart_disease.drop('target', axis=1)
y = heart_disease['target']

#split into training and test sets
x_train, x_test, y_train, y_test = train_test_split(x,
                                                    y,
                                                    test_size=0.2)
#instantiate model 
clf = RandomForestClassifier(n_estimators=100)
clf.fit(x_train, y_train);

In [103]:
clf.score(x_test, y_test)

0.8524590163934426

In [105]:
cross_val_score(clf, x, y, cv=5) #cv = cross_validation

array([0.80327869, 0.86885246, 0.78688525, 0.81666667, 0.78333333])

In [106]:
cross_val_score(clf, x, y, cv=10)

array([0.87096774, 0.83870968, 0.87096774, 0.87096774, 0.83870968,
       0.73333333, 0.7       , 0.86666667, 0.68965517, 0.82758621])

In [108]:
np.random.seed(42)

#single training and test split score
clf_single_score = clf.score(x_test, y_test)

#take the mean of 5-fold cross-validation score
clf_cross_val_score = np.mean(cross_val_score(clf, x, y, cv=5))

#compare the two
clf_single_score, clf_cross_val_score

(0.8524590163934426, 0.8248087431693989)

In [110]:
# Default scoring parameter of classifier = mean accuracy
clf.score(x_test, y_test)

0.8524590163934426

In [113]:
#Scoring parameter set to None by default
cross_val_score(clf, x, y, cv=5, scoring=None)

array([0.83606557, 0.8852459 , 0.81967213, 0.78333333, 0.73333333])


## Classification model evaluation metrics

1. Accuracy
2. Area under ROC curve
3. Confusion matrix
4. classification report

In [120]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

x = heart_disease.drop('target', axis=1)
y = heart_disease['target']

clf = RandomForestClassifier(n_estimators=100)
cross_val_score = cross_val_score(clf, x, y, cv=5)

In [121]:
np.mean(cross_val_score)

0.8248087431693989

In [125]:
print(f"Heart Disease Classifier Accuracy: {np.mean(cross_val_score) *100:.2f}%")

Heart Disease Classifier Accuracy: 82.48%
